# Generated by Django 4.2 on 2024-08-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_alter_comment_options_alter_idea_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='slug',
        ),
        migrations.AddField(
            model_name='comment',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')]),
        ),
    ]
